from classes import *

c1 = Cliente('Luiz', 45, 800)
c2 = Cliente('Jonathan', 48, 1397.20)
c3 = Cliente('Pedro', 23, 986.30)

print('===============================================')
print('Cliente: {} '.format(c1.nome))
print('Idade: {}'.format(c1.idade))
c1.debito_feito()
print('===============================================')
print('Cliente: {} '.format(c2.nome))
print('Idade: {}'.format(c2.idade))
c2.debito_feito()
print('===============================================')
print('Cliente: {} '.format(c3.nome))
print('Idade: {}'.format(c3.idade))
c3.debito_feito()

a1 = Aluno('Carlos', 23, 80.25)
a2 = Aluno('Lucas', 13, 65.79)
a3 = Aluno('Mathias', 19, 32.12)

print('===============================================')
print('Aluno: {} '.format(a1.nome))
print('Idade: {}'.format(a1.idade))
a1.final_semestre()
print('===============================================')
print('Aluno: {} '.format(a2.nome))
print('Idade: {}'.format(a2.idade))
a2.final_semestre()
print('===============================================')
print('Aluno: {} '.format(a3.nome))
print('Idade: {}'.format(a3.idade))
a3.final_semestre()
print('===============================================')