print("=====================================")
print("Operadores aritméticos...")
print('Adição:', 10 + 10)
print('Subtração:', 10 - 10)
print('Multiplicação:', 10 * 10)
print('Divisão Inteira: ', 10 // 3.5)
print('Potenciação: ', 10 ** 2)
print('Resto da divisão: ', 10 % 5)
print("=====================================")
